# Generated by Django 4.2.30 on 2026-08-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterceptedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=150)),
                ('recipient_username', models.CharField(max_length=150)),
                ('security_level', models.IntegerField()),
                ('raw_payload', models.JSONField()),
                ('intercepted_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercepted_packets', to='mailer.encryptedemail')),
            ],
            options={
                'ordering': ['-intercepted_at'],
            },
        ),
    ]
